language: python
python:
  - "3.6"

matrix:
  include:
    - env: VENV='2.7.14'
    - env: VENV=''

install:
  - pip install poetry
  - |
      if [ "$VENV" != "" ]; then
        virtualenv --python="$HOME/virtualenv/python$VENV/bin/python" "$HOME/virtualenvs/venv-$VENV"
        source "$HOME/virtualenvs/venv-$VENV/bin/activate"
      fi
  - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/bin/poetry install -v

script: py.test -q tests/
